### ISSUE TITLE
Convert To Cmsis

### ISSUE THREAD

**Issue by mahmoud2802** [hubmartin/WS2812B_STM32F3#2]
Hello .
I use STM32F10x.
How can i convert your project To use CMSIS ?
please help me

**Comment by hubmartin** [comment]
Hi. Did you mean converting to Standard Peripheral Library or porting to use just the registers? Because the Cmsis is already used for calling nvic and systick configuration. I can give you basic hints if you'll specify your question.

**Comment by mahmoud2802** [comment]
Hi i mean converting to  Standard Peripheral Library.
for example  :
HAL_GPIO_Init(WS2812B_PORT, &GPIO_InitStruct);=GPIO_Init(WS2812B_PORT, &GPIO_InitStructure);
i don't want use HAL library.
